services:
  nginx:
    image: "nginx:1.29.3"
    restart: always
    ports:
      - "80:80"
    environment:
      ENV_SERVER_NAME: ${SERVER_NAME}
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/templates/default.conf.template:ro
    depends_on:
      backend:
        condition: service_healthy
        required: true
      frontend:
        condition: service_healthy
        required: true

  backend:
    build: ./backend
    image: pupsiks/backend:latest
    restart: always
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget -qO - http://127.0.0.1:8080/healthcheck || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  frontend:
    build: 
      context: frontend
      args:
        VITE_API_URL: "/api/v1"
    image: pupsiks/frontend:latest
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "wget -qO - http://127.0.0.1:3000/healthcheck.txt || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  emailworker:
    build: ./emailworker
    image: pupsiks/emailworker:latest
    restart: always
    environment:
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_SENDER: ${SMTP_SENDER}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    depends_on:
      redis:
        condition: service_healthy

  db:
    image: "postgres:16"
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: pupsiks
    volumes:
      - dbdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d pupsiks"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:8.2.2-alpine"
    restart: always
    volumes:
      - redisdata:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

volumes:
  dbdata:
  redisdata:
