services:
  backend:
    build:
      context: backend
      dockerfile: Dockerfile.test
    environment:
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASS}
      RUST_LOG: debug
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy

  db:
    image: "postgres:16"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: pupsiks
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d pupsiks"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: "redis:8.2.2-alpine"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
      start_period: 5s

  tests:
    build: ./backend/tests
    environment:
      TEST_EMAIL: ${TEST_EMAIL}
    depends_on:
      - backend
